name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  REGION: europe-west2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/gmail_watcher/requirements.txt

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ env.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      env:
        REGION: europe-west2  # replace with your region
      run: |
        gcloud auth configure-docker europe-west2-docker.pkg.dev
        docker build -f src/agents/Dockerfile -t ${REGION}-docker.pkg.dev/$PROJECT_ID/ai-agent-processor/ai-agent-processor:${{ github.sha }} .
        docker push ${REGION}-docker.pkg.dev/$PROJECT_ID/ai-agent-processor/ai-agent-processor:${{ github.sha }}   

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -var="project_id=$PROJECT_ID" \
                       -var="region=${{ env.REGION }}" \
                       -var="image_tag=${{ github.sha }}" \
                       -out=tfplan

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan