name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: research-assistant-424819
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  REGION: europe-west2
  SECRETS_PROJECT_ID: "99383323365"
  WATCHER_SERVICE_ACCOUNT_ID: "service-99383323365"
  GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
  DOCKER_REGISTRY: europe-west2-docker.pkg.dev/${{ env.PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/gmail_watcher/requirements.txt
        pip install -r src/agents/requirements.txt

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build and push Docker images
      run: |
        docker build -f src/agents/Dockerfile -t ${{ env.DOCKER_REGISTRY }}/ai-agent-processor/ai-agent-processor:${{ github.sha }} .
        docker push ${{ env.DOCKER_REGISTRY }}/ai-agent-processor/ai-agent-processor:${{ github.sha }}
        cp src/cloud_logging_helper.py src/watcher_renewal/
        docker build -f src/watcher_renewal/Dockerfile -t ${{ env.DOCKER_REGISTRY }}/watcher-renewal/watcher-renewal:${{ github.sha }} src/watcher_renewal
        docker push ${{ env.DOCKER_REGISTRY }}/watcher-renewal/watcher-renewal:${{ github.sha }}
        docker tag ${{ env.DOCKER_REGISTRY }}/watcher-renewal/watcher-renewal:${{ github.sha }} ${{ env.DOCKER_REGISTRY }}/watcher-renewal/watcher-renewal:latest
        docker push ${{ env.DOCKER_REGISTRY }}/watcher-renewal/watcher-renewal:latest

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        cd terraform
        terraform init \
          -backend-config="bucket=${{ env.GCS_BUCKET_NAME }}" \
          -backend-config="prefix=terraform/state"

    - name: Terraform Plan and Apply
      run: |
        cd terraform
        terraform plan \
          -parallelism=2 \
          -var="project_id=${{ env.PROJECT_ID }}" \
          -var="region=${{ env.REGION }}" \
          -var="image_tag=${{ github.sha }}" \
          -var="secrets_project_id=${{ env.SECRETS_PROJECT_ID }}" \
          -var="ai_agent_processor_image=${{ env.DOCKER_REGISTRY }}/ai-agent-processor/ai-agent-processor:${{ github.sha }}" \
          -var="watcher_service_account_id=${{ env.WATCHER_SERVICE_ACCOUNT_ID }}" \
          -out=tfplan
        if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
          terraform apply -auto-approve -parallelism=2 tfplan
        fi
      env:
        TF_LOG: INFO